#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@wifidogx[-1]
	add ucitrack wifidogx
	set ucitrack.@wifidogx[-1].init=wifidogx-luci
	commit ucitrack
EOF

/etc/init.d/wifidogx disable

rm -f /tmp/luci-indexcache
exit 0
